os: linux
dist: focal
language: generic
sudo: required
git:
  depth: 1
addons:
  apt:
    update:
      - true
services:
#  - docker
before_install:
#  - docker pull fr3akyphantom/droid-builder:latest
before_script:
  - cd $HOME && mkdir twrp
# install repo
  - mkdir -p ~/.bin
  - PATH="${HOME}/.bin:${PATH}"
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
  - chmod a+rx ~/.bin/repo

script:
# if you have compiling problem try to uncomment  
#  - export LC_ALL=C  
#  To use the correct openjdk version
  - jdk_switcher use openjdk8
  - cd $HOME/twrp/
  - repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-8.1
  - repo sync
  - cd $HOME/twrp/ && git clone https://github.com/gokur20/twrp_xiaomi_Mi_Play.git device/xiaomi/lotus 
  - cd $HOME/twrp/   
  - . build/envsetup.sh
  - lunch omni_lotus-eng
  - mka recoveryimage
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/lotus/recovery.img $HOME/twrp/TWRP-$version-lotus-$(date +"%Y%m%d")-Unofficial.img
  - cd $HOME/twrp/
  # Optional: You might need to switch from https://transfer.sh to https://file.io
  # - curl -s --upload-file TWRP-$version-lotus-$(date +"%Y%m%d")-Unofficial.img https://transfer.sh/ && echo ""
deploy:
  skip_cleanup: true
  provider: releases
  # The secret api_key will be loaded from the environment variables
  #api_key: $GitOAUTHToken api_key deprecated, now use token
  token: $GitOAUTHToken
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false
    repo: gokur20/twrp_xiaomi_Mi_Play # Optional: If you want to deploy on different repository
    branch: main # Optional: Needs to be exact as the config branch
branches:
  only:
    - main # Set travis builder branch(es) names
  except:
    - /^(?i:untagged)-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
